### ISSUE TITLE
Print a welcome message when the program starts

### ISSUE THREAD

**Issue by claraj** [JayMCTC/guess_the_number#9]
Another issue for practicing the collaboration workflow

**Comment by JSirisavath** [comment]
Grant decided to do the uppercase issue and so I will self-assign myself to this issue
 @claraj

**Comment by claraj** [comment]
As long as you do 2 PRs and two reviews each, it doesn't matter who works on what. Make sure you both get to practice the working and pull request part of the process, and you both get to practice the reviewing part of the process.  Thanks!

**Comment by gloh1301** [comment]
Issue taken care of with welcome message branch

**Comment by JSirisavath** [comment]
#11 Pull request case to reference.
